"""followers

Revision ID: 57110f61706a
Revises: 4401d9de3352
Create Date: 2018-04-02 12:02:43.043817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57110f61706a'
down_revision = '4401d9de3352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
